version: '3'

services:

  mysql-master:
    image: mysql:8.0.26
    restart: always
    container_name: userAuth2.0
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: user_auth
    ports:
      - 3300:3306