spring:
  datasource:
    url: jdbc:mysql://localhost:3300/user_auth
    username: mysql
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  thymeleaf:
    check-template-location: false

  liquibase:
    enabled: true
    change-log: classpath:changelog/changelog-master.xml
    parameters:
      key: LiquibaseWithSpringBoot



server:
  port: 8082

ACCESS_TOKEN_PRIVATE_KEY_PATH: "access-refresh-token-keys/access-token-private.key"
ACCESS_TOKEN_PUBLIC_KEY_PATH: "access-refresh-token-keys/access-token-public.key"
REFRESH_TOKEN_PRIVATE_KEY_PATH: "access-refresh-token-keys/refresh-token-private.key"
REFRESH_TOKEN_PUBLIC_KEY_PATH: "access-refresh-token-keys/refresh-token-public.key"

access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}

refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}

logging:
  level:
    org.springframework.security: DEBUG

